# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160527_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPrestamo', models.IntegerField(max_length=10)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50, null=True)),
                ('fechaCreacion', models.DateTimeField(null=True)),
                ('fechaActualizacion', models.DateTimeField(null=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Item')),
                ('kit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Kit')),
            ],
            options={
                'ordering': ('fechaCreacion',),
            },
        ),
    ]
